### ISSUE TITLE
support for zeiss .czi files?

### ISSUE THREAD

**Issue by masterrite** [SCIInstitute/fluorender#15]
Hi -

Can you consider adding support of czi files generated by Zeiss Confocal Microscopes?

Thanks.

**Comment by basisunus** [comment]
I do want to add native czi support in FluoRender, since several users have mentioned it. But it would take some time to do so, as some other analysis functions are currently prioritized. In the meanwhile, you can link FluoRender with ImageJ or Fiji to support czi files. Watch this tutorial video for the setup: https://youtu.be/xvbz6BbdxsU

**Comment by basisunus** [comment]
@masterrite Can you provide me with some example CZI files, as I plan to spend some time to add the support in FluoRender? The example files will help me study the format. So, small files that can represent the typical use would be good. Please send files or links to my email: wanyong@cs.utah.edu. Thanks.

**Comment by basisunus** [comment]
Initial support added to the yong_experimental branch. Open new issues if there is any problem of reading CZI files.
