### ISSUE TITLE
missing libtiff with binary download on mac

### ISSUE THREAD

**Issue by jefferis** [SCIInstitute/fluorender#24]
Is there any chance that the precompiled binary [FluoRender2.30_mac64.pkg](https://github.com/SCIInstitute/fluorender/releases/download/v2.30/FluoRender2.30_mac64.pkg) could include libtiff? I am on macosx 14.5 / M3 chip and hesitating about installing homebrew intel (as would be required here) vs homebrew arm ...

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/libtiff/lib/libtiff.6.dylib
Referenced from: <C4C17092-52A0-31A9-81CE-0388E9A452F2> /Applications/FluoRender.app/Contents/MacOS/FluoRender
Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file)
(terminated at launch; ignore backtrace)
```

**Comment by basisunus** [comment]
That should be easy to add. I’ll find a proper solution and put it on the github as soon as possible.

Thanks,
Yong

From: Gregory Jefferis ***@***.***>
Sent: Monday, June 24, 2024 2:48 AM
To: SCIInstitute/fluorender ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SCIInstitute/fluorender] missing libtiff with binary download on (Issue #24)


Is there any chance that the precompiled binary FluoRender2.30_mac64.pkg<https://github.com/SCIInstitute/fluorender/releases/download/v2.30/FluoRender2.30_mac64.pkg> could include libtiff? I am on macosx 14.5 / M3 chip and hesitating about installing homebrew intel (as would be required here) vs homebrew arm ...

Termination Reason:    Namespace DYLD, Code 1 Library missing

Library not loaded: /usr/local/opt/libtiff/lib/libtiff.6.dylib

Referenced from: <C4C17092-52A0-31A9-81CE-0388E9A452F2> /Applications/FluoRender.app/Contents/MacOS/FluoRender

Reason: tried: '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file), '/usr/local/opt/libtiff/lib/libtiff.6.dylib' (no such file)

(terminated at launch; ignore backtrace)

**Comment by gregorycu** [comment]
Please also consider libaec and libjpeg (Maybe see what libraries it loads on MacOS and deploy them too).

**Comment by basisunus** [comment]
For the release of version 2.31, these dependencies have been linked as static libraries: libfreetype, libjpeg, libtiff, libhdf5. The dependency of libaec came from libhdf5, which should be included with it. The best practice seems to make the dependencies from the source code instead of using Homebrew. This is especially crucial for libhdf5. Version 2.31 also added the dependency to Python on Mac OS, which came from Dlib, which is currently used in FluoRender for deep neural network evaluations. This is resolved by adding a postinsall script in the pkg installer to download and install Python on Mac. The installer has been tested on users' computers that originally lacked the dependent libraries.
